export const APP = {
    ACTION_SET_DARK_MODE: "ACTION_SET_DARK_MODE",
    ACTION_SET_SHOW_APP_BAR: "ACTION_SET_SHOW_APP_BAR",
    ACTION_SET_APP_BAR_TITLE: "ACTION_SET_APP_BAR_TITLE",
    ACTION_SET_SHOW_SOURCE_CODE_LINK: "ACTION_SET_SHOW_SOURCE_CODE_LINK"
}
